[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_WALLETCONNECT_PROJECT_ID = "519a1ef92a4bcca36c38e881aefcc324"
  VITE_GENESIS_BADGE_CONTRACT = "0x18Cd3974357FfC524E4Ee2D3e08b06eD3E0B7E1C"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200