[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_ANALYTICS_ID = "YOUR_ID"

[context.production.environment]
  NEXT_PUBLIC_ENV = "production"

[context.deploy-preview.environment]
  NEXT_PUBLIC_ENV = "staging"

# Next.js specific optimizations
[plugins]
  [[plugins.inputs]]
    package = "@netlify/plugin-nextjs"

# Redirects for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Edge Functions (optional)
[[edge_functions]]
  path = "/api/*"
  function = "api"